\doxysection{D\+:/\+GIT/\+Food\+Link/foodlink.client/node\+\_\+modules/p-\/retry Directory Reference}
\hypertarget{dir_c7fabb7a2ff3abb0a701d228f41ffa12}{}\label{dir_c7fabb7a2ff3abb0a701d228f41ffa12}\index{D:/GIT/FoodLink/foodlink.client/node\_modules/p-\/retry Directory Reference@{D:/GIT/FoodLink/foodlink.client/node\_modules/p-\/retry Directory Reference}}


\doxysubsection{Detailed Description}
\begin{quote}
Retry a promise-\/returning or async function \end{quote}


It does exponential backoff and supports custom retry strategies for failed operations.\hypertarget{readme.md_autotoc_md15853}{}\doxysubsection{\texorpdfstring{Install}{Install}}\label{readme.md_autotoc_md15853}

\begin{DoxyCode}{0}
\DoxyCodeLine{\$\ npm\ install\ p-\/retry}

\end{DoxyCode}
\hypertarget{readme.md_autotoc_md15854}{}\doxysubsection{\texorpdfstring{Usage}{Usage}}\label{readme.md_autotoc_md15854}

\begin{DoxyCode}{0}
\DoxyCodeLine{const\ pRetry\ =\ require('p-\/retry');}
\DoxyCodeLine{const\ fetch\ =\ require('node-\/fetch');}
\DoxyCodeLine{}
\DoxyCodeLine{const\ run\ =\ async\ ()\ =>\ \{}
\DoxyCodeLine{\ \ \ \ const\ response\ =\ await\ fetch('https://sindresorhus.com/unicorn');}
\DoxyCodeLine{}
\DoxyCodeLine{\ \ \ \ //\ Abort\ retrying\ if\ the\ resource\ doesn't\ exist}
\DoxyCodeLine{\ \ \ \ if\ (response.status\ ===\ 404)\ \{}
\DoxyCodeLine{\ \ \ \ \ \ \ \ throw\ new\ pRetry.AbortError(response.statusText);}
\DoxyCodeLine{\ \ \ \ \}}
\DoxyCodeLine{}
\DoxyCodeLine{\ \ \ \ return\ response.blob();}
\DoxyCodeLine{\};}
\DoxyCodeLine{}
\DoxyCodeLine{(async\ ()\ =>\ \{}
\DoxyCodeLine{\ \ \ \ console.log(await\ pRetry(run,\ \{retries:\ 5\}));}
\DoxyCodeLine{\})();}

\end{DoxyCode}
\hypertarget{readme.md_autotoc_md15855}{}\doxysubsection{\texorpdfstring{API}{API}}\label{readme.md_autotoc_md15855}
\hypertarget{readme.md_autotoc_md15856}{}\doxysubsubsection{\texorpdfstring{p\+Retry(input, options?)}{p\+Retry(input, options?)}}\label{readme.md_autotoc_md15856}
Returns a {\ttfamily Promise} that is fulfilled when calling {\ttfamily input} returns a fulfilled promise. If calling {\ttfamily input} returns a rejected promise, {\ttfamily input} is called again until the maximum number of retries is reached. It then rejects with the last rejection reason.

Does not retry on most {\ttfamily Type\+Errors}, with the exception of network errors. This is done on a best case basis as different browsers have different \href{https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch\#Checking_that_the_fetch_was_successful}{\texttt{ messages}} to indicate this. See \href{https://github.com/whatwg/fetch/issues/526\#issuecomment-554604080}{\texttt{ whatwg/fetch\#526 (comment)}}\hypertarget{readme.md_autotoc_md15857}{}\doxysubsubsubsection{\texorpdfstring{input}{input}}\label{readme.md_autotoc_md15857}
Type\+: {\ttfamily Function}

Receives the current attempt number as the first argument and is expected to return a {\ttfamily Promise} or any value.\hypertarget{readme.md_autotoc_md15858}{}\doxysubsubsubsection{\texorpdfstring{options}{options}}\label{readme.md_autotoc_md15858}
Type\+: {\ttfamily object}

Options are passed to the \href{https://github.com/tim-kos/node-retry\#retryoperationoptions}{\texttt{ {\ttfamily retry}}} module.\hypertarget{readme.md_autotoc_md15859}{}\doxysubsubsubsubsection{\texorpdfstring{on\+Failed\+Attempt(error)}{on\+Failed\+Attempt(error)}}\label{readme.md_autotoc_md15859}
Type\+: {\ttfamily Function}

Callback invoked on each retry. Receives the error thrown by {\ttfamily input} as the first argument with properties {\ttfamily attempt\+Number} and {\ttfamily retries\+Left} which indicate the current attempt number and the number of attempts left, respectively.


\begin{DoxyCode}{0}
\DoxyCodeLine{const\ run\ =\ async\ ()\ =>\ \{}
\DoxyCodeLine{\ \ \ \ const\ response\ =\ await\ fetch('https://sindresorhus.com/unicorn');}
\DoxyCodeLine{}
\DoxyCodeLine{\ \ \ \ if\ (!response.ok)\ \{}
\DoxyCodeLine{\ \ \ \ \ \ \ \ throw\ new\ Error(response.statusText);}
\DoxyCodeLine{\ \ \ \ \}}
\DoxyCodeLine{}
\DoxyCodeLine{\ \ \ \ return\ response.json();}
\DoxyCodeLine{\};}
\DoxyCodeLine{}
\DoxyCodeLine{(async\ ()\ =>\ \{}
\DoxyCodeLine{\ \ \ \ const\ result\ =\ await\ pRetry(run,\ \{}
\DoxyCodeLine{\ \ \ \ \ \ \ \ onFailedAttempt:\ error\ =>\ \{}
\DoxyCodeLine{\ \ \ \ \ \ \ \ \ \ \ \ console.log(`Attempt\ \$\{error.attemptNumber\}\ failed.\ There\ are\ \$\{error.retriesLeft\}\ retries\ left.`);}
\DoxyCodeLine{\ \ \ \ \ \ \ \ \ \ \ \ //\ 1st\ request\ =>\ Attempt\ 1\ failed.\ There\ are\ 4\ retries\ left.}
\DoxyCodeLine{\ \ \ \ \ \ \ \ \ \ \ \ //\ 2nd\ request\ =>\ Attempt\ 2\ failed.\ There\ are\ 3\ retries\ left.}
\DoxyCodeLine{\ \ \ \ \ \ \ \ \ \ \ \ //\ â€¦}
\DoxyCodeLine{\ \ \ \ \ \ \ \ \},}
\DoxyCodeLine{\ \ \ \ \ \ \ \ retries:\ 5}
\DoxyCodeLine{\ \ \ \ \});}
\DoxyCodeLine{}
\DoxyCodeLine{\ \ \ \ console.log(result);}
\DoxyCodeLine{\})();}

\end{DoxyCode}


The {\ttfamily on\+Failed\+Attempt} function can return a promise. For example, you can do some async logging\+:


\begin{DoxyCode}{0}
\DoxyCodeLine{const\ pRetry\ =\ require('p-\/retry');}
\DoxyCodeLine{const\ logger\ =\ require('./some-\/logger');}
\DoxyCodeLine{}
\DoxyCodeLine{const\ run\ =\ async\ ()\ =>\ \{\ â€¦\ \};}
\DoxyCodeLine{}
\DoxyCodeLine{(async\ ()\ =>\ \{}
\DoxyCodeLine{\ \ \ \ const\ result\ =\ await\ pRetry(run,\ \{}
\DoxyCodeLine{\ \ \ \ \ \ \ \ onFailedAttempt:\ async\ error\ =>\ \{}
\DoxyCodeLine{\ \ \ \ \ \ \ \ \ \ \ \ await\ logger.log(error);}
\DoxyCodeLine{\ \ \ \ \ \ \ \ \}}
\DoxyCodeLine{\ \ \ \ \});}
\DoxyCodeLine{\})();}

\end{DoxyCode}


If the {\ttfamily on\+Failed\+Attempt} function throws, all retries will be aborted and the original promise will reject with the thrown error.\hypertarget{readme.md_autotoc_md15860}{}\doxysubsubsection{\texorpdfstring{p\+Retry.\+Abort\+Error(message)}{p\+Retry.\+Abort\+Error(message)}}\label{readme.md_autotoc_md15860}
\hypertarget{readme.md_autotoc_md15861}{}\doxysubsubsection{\texorpdfstring{p\+Retry.\+Abort\+Error(error)}{p\+Retry.\+Abort\+Error(error)}}\label{readme.md_autotoc_md15861}
Abort retrying and reject the promise.\hypertarget{readme.md_autotoc_md15862}{}\doxysubsubsection{\texorpdfstring{message}{message}}\label{readme.md_autotoc_md15862}
Type\+: {\ttfamily string}

Error message.\hypertarget{readme.md_autotoc_md15863}{}\doxysubsubsection{\texorpdfstring{error}{error}}\label{readme.md_autotoc_md15863}
Type\+: {\ttfamily Error}

Custom error.\hypertarget{readme.md_autotoc_md15864}{}\doxysubsection{\texorpdfstring{Tip}{Tip}}\label{readme.md_autotoc_md15864}
You can pass arguments to the function being retried by wrapping it in an inline arrow function\+:


\begin{DoxyCode}{0}
\DoxyCodeLine{const\ pRetry\ =\ require('p-\/retry');}
\DoxyCodeLine{}
\DoxyCodeLine{const\ run\ =\ async\ emoji\ =>\ \{}
\DoxyCodeLine{\ \ \ \ //\ â€¦}
\DoxyCodeLine{\};}
\DoxyCodeLine{}
\DoxyCodeLine{(async\ ()\ =>\ \{}
\DoxyCodeLine{\ \ \ \ //\ Without\ arguments}
\DoxyCodeLine{\ \ \ \ await\ pRetry(run,\ \{retries:\ 5\});}
\DoxyCodeLine{}
\DoxyCodeLine{\ \ \ \ //\ With\ arguments}
\DoxyCodeLine{\ \ \ \ await\ pRetry(()\ =>\ run('ðŸ¦„'),\ \{retries:\ 5\});}
\DoxyCodeLine{\})();}

\end{DoxyCode}
\hypertarget{readme.md_autotoc_md15865}{}\doxysubsection{\texorpdfstring{Related}{Related}}\label{readme.md_autotoc_md15865}

\begin{DoxyItemize}
\item \href{https://github.com/sindresorhus/p-timeout}{\texttt{ p-\/timeout}} -\/ Timeout a promise after a specified amount of time
\item \href{https://github.com/sindresorhus/promise-fun}{\texttt{ Moreâ€¦}} 
\end{DoxyItemize}